default:
  sessions:
    default:
      database: admin
      username: admin
      password: mongodb_rails
      hosts:
        - 192.168.0.20:27017
  options:
    identity_map_enabled: true

development:
  sessions:
    default:
      database: admin
      username: admin
      password: mongodb_rails
      hosts:
        - 192.168.0.20:27017
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      database: locomotive_test
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      database: admin
      username: admin
      password: mongodb_rails
      hosts:
        - 192.168.0.20:27017
  options:
    identity_map_enabled: true
